language: java
jdk:
  - openjdk8

sudo: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:

    - stage: build
      script:
        - ./gradlew clean build

    - stage: publish
      if: branch = master
      script:
        - ./gradlew publishPlugins -Pgradle.publish.key="$GRADLE_PUBLISH_KEY" -Pgradle.publish.secret="$GRADLE_PUBLISH_SECRET"